export const protocolData = [
  {
    name: "Uniswap",
    category: "Dexes",
    tvl: "$3.972b",
    fees: "$937,807",
    revenue: "$0",
    icon: "uniswap",
    slug: "uniswap",
  },
  {
    name: "SushiSwap",
    category: "Dexes",
    tvl: "$3.972b",
    fees: "$937,807",
    revenue: "$0",
    icon: "sushi",
    slug: "sushiswap",
  },
  {
    name: "Compound Finance",
    category: "Lending",
    tvl: "$1.914b",
    fees: "$29,944",
    revenue: "$4,828",
    icon: "compound",
    slug: "compound",
  },
  {
    name: "AAVE",
    category: "Lending",
    tvl: "$11.933b",
    fees: "$922,124",
    revenue: "$340,549",
    icon: "aave",
    slug: "aave",
  },
  {
    name: "Lido",
    category: "Liquid-Staking",
    tvl: "$26.027b",
    fees: "$2.09m",
    revenue: "$208,733",
    icon: "lido",
    slug: "lido",
  },
  {
    name: "Rocket Pool",
    category: "Liquid-Staking",
    tvl: "$3.436b",
    fees: "-",
    revenue: "-",
    icon: "rocketPool",
    slug: "rocketpool",
  },
  {
    name: "Ondo Finance",
    category: "RWA",
    tvl: "$446.21m",
    fees: "$446.21m",
    revenue: "$446.21m",
    icon: "ondo",
    slug: "ondo",
  },
  {
    name: "EigenLayer",
    category: "Restaking",
    tvl: "$446.21m",
    fees: "$446.21m",
    revenue: "$446.21m",
    icon: "eigenLayer",
    slug: "eigenlayer",
  },
  {
    name: "EtherFi",
    category: "Restaking",
    tvl: "$446.21m",
    fees: "$446.21m",
    revenue: "$446.21m",
    icon: "etherfi",
    slug: "etherfi",
  },
];

export const portfolioTokens = [
  {
    name: "Ethereum",
    symbol: "ETH",
    icon: "ethereum.png",
    balance: "$0",
    change: "0%",
  },
  {
    name: "BSC",
    symbol: "BSC",
    icon: "svgs/bsc.svg",
    balance: "$0",
    change: "0%",
  },
  {
    name: "Base",
    symbol: "BASE",
    icon: "svgs/baseColor.svg",
    balance: "$0",
    change: "0%",
  },
  {
    name: "Arbitrum",
    symbol: "ARB",
    icon: "svgs/arbitriumColor.svg",
    balance: "$0",
    change: "0%",
  },
  {
    name: "Avalanche",
    symbol: "AVAX",
    icon: "svgs/avalanche.svg",
    balance: "$0",
    change: "0%",
  },
];

// For Compound Finance
export const AssetsSupplyData = [
  {
    id: 1,
    label: "ChainLink",
    img: "/svgs/chainLink.svg",
    apy: "2.04%",
    balance: 0,
    token: "LINK",
    walletBalance: "0",
    change: "+5.2%",
  },
  {
    id: 2,
    label: "ChainLink",
    img: "/svgs/chainLink.svg",
    apy: "2.04%",
    balance: 0,
    token: "LINK",
    walletBalance: "0",
    change: "-2.1%",
  },
  {
    id: 3,
    label: "ChainLink",
    img: "/svgs/chainLink.svg",
    apy: "2.04%",
    balance: 0,
    token: "LINK",
    walletBalance: "0",
    change: "+1.8%",
  },
];

export const AssetsBorrowData = [
  {
    id: 1,
    icon: "/svgs/eth.svg",
    label: "ETH",
    balance: 0,
    apy: "3.5%",
  },
  {
    id: 2,
    icon: "/svgs/eth.svg",
    label: "ETH",
    balance: 0,
    apy: "3.2%",
  },
  {
    id: 3,
    icon: "/svgs/eth.svg",
    label: "ETH",
    balance: 0,
    apy: "2.8%",
  },
  {
    id: 4,
    icon: "/svgs/eth.svg",
    label: "ETH",
    balance: 0,
    apy: "4.1%",
  },
  {
    id: 5,
    icon: "/svgs/eth.svg",
    label: "ETH",
    balance: 0,
    apy: "3.7%",
  },
];
