export const protocolData = [
  {
    name: "Uniswap",
    category: "Dexes",
    tvl: "$3.972b",
    fees: "$937,807",
    revenue: "$0",
    icon: "uniswap",
    slug: "uniswap",
  },
  {
    name: "SushiSwap",
    category: "Dexes",
    tvl: "$3.972b",
    fees: "$937,807",
    revenue: "$0",
    icon: "sushi",
    slug: "sushiswap",
  },
  {
    name: "Compound Finance",
    category: "Lending",
    tvl: "$1.914b",
    fees: "$29,944",
    revenue: "$4,828",
    icon: "compound",
    slug: "compound",
  },
  {
    name: "AAVE",
    category: "Lending",
    tvl: "$11.933b",
    fees: "$922,124",
    revenue: "$340,549",
    icon: "aave",
    slug: "aave",
  },
  {
    name: "Lido",
    category: "Liquid-Staking",
    tvl: "$26.027b",
    fees: "$2.09m",
    revenue: "$208,733",
    icon: "lido",
    slug: "lido",
  },
  {
    name: "Rocket Pool",
    category: "Liquid Staking",
    tvl: "$3.436b",
    fees: "-",
    revenue: "-",
    icon: "rocketPool",
    slug: "rocketpool",
  },
  {
    name: "Ondo Finance",
    category: "RWA",
    tvl: "$446.21m",
    fees: "$446.21m",
    revenue: "$446.21m",
    icon: "ondo",
    slug: "ondo",
  },
  {
    name: "EigenLayer",
    category: "Restaking",
    tvl: "$446.21m",
    fees: "$446.21m",
    revenue: "$446.21m",
    icon: "eigenLayer",
    slug: "eigenlayer",
  },
  {
    name: "EtherFi",
    category: "Restaking",
    tvl: "$446.21m",
    fees: "$446.21m",
    revenue: "$446.21m",
    icon: "etherfi",
    slug: "etherfi",
  },
];
